// config.js

export var LS='tj.data.v1';
export var LSU='tj.ui.v1';
export var NEWS_URL='https://nfs.faireconomy.media/ff_calendar_thisweek.json';
export var FF_URL='https://www.forexfactory.com/calendar';
export var DEFAULT_BEHAVIORS=['Hesitated on the A+','Forced one after missing it','Fought the magnet line','Added filters'];
export var RULES=[
 'Verify account counts, lineup order, balances and classifications against the screenshots before saying anything is done.',
 'Never invent accounts, balances or statuses — only record what a screenshot or the user actually provided.',
 'Fixes apply retroactively: correcting a record recalculates every total, stop and record derived from it.',
 'Balances only change through dated imports — no free editing of balances anywhere else.',
 'Never report progress, balances or fills that were not provided.'
];
/* Generic starter firms shown in onboarding and used by the demo. Users rename them / add their own firms in
   Get started or Settings ▸ Firms (buffer, trader share %, short name, plan and an optional Rules link). */
export var FIRM_PRESETS=[
  {name:'Firm A',buffer:1500,share:80,short:'FA',plan:''},
  {name:'Firm B',buffer:1000,share:90,short:'FB',plan:''},
  {name:'Firm C',buffer:1100,share:90,short:'FC',plan:''}];
export var APP_NAME='Trading Journal';
/* ---- Accounts (Supabase). Leave both empty → "Test mode" (accounts stored only on this device).
   Paste from Supabase → Project Settings → API Keys: the Project URL and the PUBLISHABLE key (sb_publishable_…;
   the legacy "anon" key also works). It is public by design — Row Level Security (supabase/schema.sql) protects
   the data. Never put a secret (sb_secret_…) or service_role key here. */
export var SUPABASE_URL='https://jrcozcrfbjcsuqkmoaki.supabase.co';
export var SUPABASE_ANON_KEY='sb_publishable_cAiiq9Vv_9H_3ZCGD6yOXA_NeDnSkAe';
export var SUPABASE_CDN='https://esm.sh/@supabase/supabase-js@2.117.2';
/* where email links (confirm / reset password) return to; empty = the current page */
/* legal + support pages live in the Pages repo (legal/, support/). Web: relative to the app root;
   native (Capacitor) / file://: absolute on SITE_URL. */
export var SITE_URL='https://billyhomer12-jpg.github.io/trading-journal/';
export var LINKS={terms:'legal/terms.html',privacy:'legal/privacy.html',support:'support/',deleteAccount:'legal/delete-account.html',disclaimer:'legal/disclaimer.html'};
export var AUTH_REDIRECT='https://billyhomer12-jpg.github.io/trading-journal/';
/* OAuth buttons enable only when listed here AND configured in Supabase. Apple guideline 4.8: if 'google' is
   offered, 'apple' must be offered too — Google stays disabled unless Apple is enabled. e.g. ['apple','google'] */
export var OAUTH_PROVIDERS=[];
/* true = the sign-in screen offers "Not now" (journal works without an account; Apple 5.1.1 discourages forced
   sign-in when the core features don't need an account). false = an account is required. */
export var ALLOW_GUEST=true;
/* Accent themes: [id, name, swatch from, swatch to]. Tokens live in styles.css (Sea Green = the :root defaults,
   the rest are generated by tools/gen-themes.js). Gain/loss green/red never change with the theme. */
export var THEMES=[['sea','Sea Green','#7fe8c8','#0e8f7a'],['teal','Teal','#7fe4e8','#0e788f'],['ocean','Ocean Blue','#7fbee8','#0e498f'],['violet','Violet','#9687e0','#3a1885'],['graphite','Graphite','#acb5bb','#454e58']];
export var APPEARANCE=[['light','Light'],['dark','Dark'],['auto','System']];
/* 'modular' = app/ (PWA, Capacitor). build.js rewrites this to 'single' for the one-file build (no service worker there). */
export var BUILD='modular';
